language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
    - klinton1991@gmail.com
    on_success: always
    on_failure: always
script: mvn clean test