language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
    - klinton1991@gmail.com
    on_success: always
    on_failure: always
before_script:
  # Install Chrome driver
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/

  # For selenium in headless linux system, But no need when PhantomJS
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: mvn clean test